try {
    console.log('hello)
} catch(e) {
    console.log('caught')
}